### ISSUE TITLE
handleNewUserMessage is doing nothing ?

### ISSUE THREAD

**Issue by Draym** [Wolox/react-chat-widget#200]
Hello,

I have just installed react-chat-widget and set it up correctly.

I can add messages to it using addResponseMessage and everything looks good.

BUT when I enter some text in the chat input and press 'enter' or click on the send button, nothing is happening. Nothing in the console as well, no errors or logs from the handleNewUserMessage callback.

I don't get it as it's the most basic feature.

```
import React, {useEffect} from "react";
import {addResponseMessage, Widget} from "react-chat-widget";

import "react-chat-widget/lib/styles.css";

function App() {
    useEffect(() => {
        addResponseMessage("Hello");
        addResponseMessage("What would you like to do ?");
    }, []);

    const handleNewUserMessage = (newMessage) => {
        console.log("New message incoming!", newMessage);
        // Now send the message throught the backend API
        addResponseMessage("ok");
    };

    return (
        <div className="App">
            <Widget
                handleNewUserMessage={handleNewUserMessage}>
        </div>
    );
}
```

any help would be welcome, thanks

**Comment by mcallegari10** [comment]
Hi @Draym ! Thank you for the heads up. I just published v3.0.4, it should be fixed! Sorry for the inconvenience. Feel free to reopen if needed 😄

**Comment by naser-baig-au4** [comment]
Hi @mcallegari10, I have just updated to 3.0.4 and the issue still persists. Can we please reopen this?

**Comment by AnemosGroup** [comment]
Happens the same to me, version 3.0.4.
"react": "^16.8.6"

**Comment by naser-baig-au4** [comment]
Tested and works like a charm. Thanks @mcallegari10 :)

Try reinstalling the chat-widget if it doesn't work for you after updating. It did for me that way.

**Comment by meksikann** [comment]
It works. thanks and  #202 fixed also in v3.0.5

**Comment by Draym** [comment]
@mcallegari10 really a big thanks for your fast fix (few minutes), really awesome. Thanks to it, I have added a callback to make it works on the previous version, it was for an urgent prototype. So you saved my day.

I have tried to the new version and it's working just fine as expected now 😄
